import Mathlib
import Definitions.Def_ModularCurve_JLinePlaces
import Definitions.Def_AlgebraicCurve_DivisorPushPull
import Definitions.Def_ModularCurve_GenusNumerics
import P2M.Util
import P2M.Sol.S_ModularCurve_deg_jLinePlace1728

open IntermediateField AlgebraicCurve
theorem ModularCurve.deg_jLinePlace1728 : ModularCurve.jLinePlace1728.deg = 1 := by p2m_exact_reverting @_root_.P2MW.S_ModularCurve_deg_jLinePlace1728.solution
