import Definitions.Def_EllipticCurve_RubinSilverbergFamily
import Definitions.Def_FLTPrelim_GaloisRep
import P2M.Util
import P2M.Sol.S_RubinSilverberg_exists_torsionBy_linearEquiv_rsMember
attribute [-instance] WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly
attribute [-simp] compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two

open WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point RubinSilverberg
open scoped Classical
theorem RubinSilverberg.exists_torsionBy_linearEquiv_rsMember (a b l t₀ : ℚ) (ha : a ≠ 0) (hb : b ≠ 0) (u₀ : AlgebraicClosure ℚ) (h₀ : IsKleinDatum (algebraMap ℚ (AlgebraicClosure ℚ) a) (algebraMap ℚ (AlgebraicClosure ℚ) b) u₀) (W₁ : WeierstrassCurve ℚ) (hW₁ : W₁.map (algebraMap ℚ (AlgebraicClosure ℚ)) = rsMember (algebraMap ℚ (AlgebraicClosure ℚ) a) (algebraMap ℚ (AlgebraicClosure ℚ) b) u₀ (algebraMap ℚ (AlgebraicClosure ℚ) l) (algebraMap ℚ (AlgebraicClosure ℚ) t₀)) (hΔ₁ : W₁.Δ ≠ 0) : ∃ φ : Submodule.torsionBy ℤ ((⟨0, 0, 0, a, b⟩ : WeierstrassCurve ℚ)⁄(AlgebraicClosure ℚ)).Point (5 : ℕ) ≃ₗ[ZMod 5] Submodule.torsionBy ℤ (W₁⁄(AlgebraicClosure ℚ)).Point (5 : ℕ), ∀ (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (x : Submodule.torsionBy ℤ ((⟨0, 0, 0, a, b⟩ : WeierstrassCurve ℚ)⁄(AlgebraicClosure ℚ)).Point (5 : ℕ)), φ (σ • x) = σ • φ x := by p2m_exact_reverting @_root_.P2MW.S_RubinSilverberg_exists_torsionBy_linearEquiv_rsMember.solution
