import Mathlib
import Definitions.Def_WeierstrassCurve_RationalEnd
import Definitions.Def_WeierstrassCurve_ReduceHom
import Definitions.Def_WeierstrassCurve_VariableChangePointEquiv
import Definitions.Def_WeierstrassCurve_RatPointHom
import P2M.Util
import P2M.Sol.S_WeierstrassCurve_exists_reduceHom_comp_eq_of_exists_reduceHom_comp_eq_map_iterateFrobenius
attribute [-simp] WeierstrassCurve.pointAddEquivOfEq_refl

theorem WeierstrassCurve.exists_reduceHom_comp_eq_of_exists_reduceHom_comp_eq_map_iterateFrobenius (p : ℕ) [Fact p.Prime] (A : ValuationSubring (AlgebraicClosure ℚ)) [DecidableEq (AlgebraicClosure ℚ)] [DecidableEq (IsLocalRing.ResidueField A)] [CharP (IsLocalRing.ResidueField A) p] (n : ℕ) (W : WeierstrassCurve (IsLocalRing.ResidueField A)) [W.IsElliptic] (β : W.toAffine.Point →+ W.toAffine.Point) {β' : (W.map (iterateFrobenius (IsLocalRing.ResidueField A) p n)).toAffine.Point →+ (W.map (iterateFrobenius (IsLocalRing.ResidueField A) p n)).toAffine.Point} (hβ' : β'.comp (WeierstrassCurve.ratPointHom (iterateFrobenius (IsLocalRing.ResidueField A) p n)) = (WeierstrassCurve.ratPointHom (iterateFrobenius (IsLocalRing.ResidueField A) p n)).comp β) (hlift : ∃ (E' : WeierstrassCurve A) (hΔ' : (E'.map (IsLocalRing.residue A)).Δ ≠ 0) (v' : WeierstrassCurve.VariableChange (IsLocalRing.ResidueField A)) (hv' : v' • E'.map (IsLocalRing.residue A) = W.map (iterateFrobenius (IsLocalRing.ResidueField A) p n)), ∃ α' ∈ WeierstrassCurve.rationalHomSet (AlgebraicClosure ℚ) (E'.map A.subtype) (E'.map A.subtype), ∀ P : (E'.map A.subtype).toAffine.Point, (WeierstrassCurve.Affine.Point.equivOfVariableChangeEq hv').symm (WeierstrassCurve.reduceHom hΔ' (α' P)) = β' ((WeierstrassCurve.Affine.Point.equivOfVariableChangeEq hv').symm (WeierstrassCurve.reduceHom hΔ' P))) : ∃ (E : WeierstrassCurve A) (hΔ : (E.map (IsLocalRing.residue A)).Δ ≠ 0) (v : WeierstrassCurve.VariableChange (IsLocalRing.ResidueField A)) (hv : v • E.map (IsLocalRing.residue A) = W), ∃ α ∈ WeierstrassCurve.rationalHomSet (AlgebraicClosure ℚ) (E.map A.subtype) (E.map A.subtype), ∀ P : (E.map A.subtype).toAffine.Point, (WeierstrassCurve.Affine.Point.equivOfVariableChangeEq hv).symm (WeierstrassCurve.reduceHom hΔ (α P)) = β ((WeierstrassCurve.Affine.Point.equivOfVariableChangeEq hv).symm (WeierstrassCurve.reduceHom hΔ P)) := by p2m_exact_reverting @_root_.P2MW.S_WeierstrassCurve_exists_reduceHom_comp_eq_of_exists_reduceHom_comp_eq_map_iterateFrobenius.solution
