import Definitions.Def_EllipticCurve_RubinSilverbergFamily
import Definitions.Def_FieldTheory_RatFuncTower
import Definitions.Def_FLTPrelim_GaloisRep
import P2M.Util
import P2M.Sol.S_WeierstrassCurve_exists_specializationHom
attribute [-instance] WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly
attribute [-simp] compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two

open Polynomial WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point RubinSilverberg RatFuncTower
open scoped Classical
theorem WeierstrassCurve.exists_specializationHom (W : WeierstrassCurve (Polynomial ℚ)) (t₀ : ℚ) (hΔ : W.Δ.eval t₀ ≠ 0) : ∃ s : (W⁄(FractionRing (Polynomial (AlgebraicClosure ℚ)))).Point →+ ((W.map (Polynomial.evalRingHom t₀))⁄(AlgebraicClosure ℚ)).Point, (∀ (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (P : (W⁄(FractionRing (Polynomial (AlgebraicClosure ℚ)))).Point), s (galLift σ • P) = σ • s P) ∧ (∀ (n : ℕ), n ≠ 0 → ∀ P : (W⁄(FractionRing (Polynomial (AlgebraicClosure ℚ)))).Point, n • P = 0 → s P = 0 → P = 0) ∧ (∀ (x y : Polynomial (AlgebraicClosure ℚ)) (h : (W⁄(FractionRing (Polynomial (AlgebraicClosure ℚ)))).toAffine.Nonsingular (algebraMap (Polynomial (AlgebraicClosure ℚ)) (FractionRing (Polynomial (AlgebraicClosure ℚ))) x) (algebraMap (Polynomial (AlgebraicClosure ℚ)) (FractionRing (Polynomial (AlgebraicClosure ℚ))) y)), s (Point.some (algebraMap (Polynomial (AlgebraicClosure ℚ)) (FractionRing (Polynomial (AlgebraicClosure ℚ))) x) (algebraMap (Polynomial (AlgebraicClosure ℚ)) (FractionRing (Polynomial (AlgebraicClosure ℚ))) y) h) = pt ((W.map (Polynomial.evalRingHom t₀)).baseChange (AlgebraicClosure ℚ)) (x.eval (algebraMap ℚ (AlgebraicClosure ℚ) t₀)) (y.eval (algebraMap ℚ (AlgebraicClosure ℚ) t₀))) := by p2m_exact_reverting @_root_.P2MW.S_WeierstrassCurve_exists_specializationHom.solution
